apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent
  namespace: dev
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: agent
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
