apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gnaiem686/polyai-frontend:098fabec768d52ace61e41047b177787df644a7f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: AGENT_URL
              value: "http://agent-svc:8000"
            - name: NEXT_PUBLIC_AGENT_URL
              value: "https://agent-dev.gnaiem.fursa.click"
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
