apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: dev
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: gnaiem686/polyai-yolo:ca1dd05312842e3523f936104fff41bb9cf62a57
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_S3_BUCKET
              value: "gnaiem-polyai-images"
            - name: YOLO_CONFIG_DIR
              value: "/tmp/Ultralytics"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
