controller:
  replicaCount: 2

  config:
    use-forwarded-headers: "true"
    proxy-real-ip-cidr: "10.0.0.0/16"

  service:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: __HTTP_NODE_PORT__
      https: __HTTPS_NODE_PORT__

  metrics:
    enabled: true
    service:
      enabled: true

  admissionWebhooks:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

defaultBackend:
  enabled: false
