apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-proc-mcp
  namespace: prod
  labels:
    app: img-proc-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img-proc-mcp
  template:
    metadata:
      labels:
        app: img-proc-mcp
    spec:
      containers:
        - name: img-proc-mcp
          image: gnaiem686/polyai-img-proc-mcp:c83af6f6a0ef6221b414a4f713127dfc9f9dcafa
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
          env:
            - name: PORT
              value: "8100"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_S3_BUCKET
              value: "gnaiem-polyai-images"
