apiVersion: v1
kind: Service
metadata:
  name: yolo-svc
  namespace: prod
  labels:
    app: yolo
spec:
  type: ClusterIP
  selector:
    app: yolo
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
